### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by Minywire** [Minywire/Bottlebrush_Engine#100]
# Things to do (in order)

- [x] Read light properties from scripting
- [ ] Implement materials from .mtl file
- [x] Implement directional light
- [x] Terrain lighting

**Comment by The-Spaghetti-Is-Ready** [comment]
Might need to fix that order, scripting functionality assumes that a feature is complete so we may need to do this at the end of light implementation to avoid juggling frontend and backend stacks.

**Comment by The-Spaghetti-Is-Ready** [comment]
scrapping .mtl file implementation
