### ISSUE TITLE
Input Manager

### ISSUE THREAD

**Issue by Minywire** [Minywire/Bottlebrush_Engine#83]
Create an input management system that allows user control inputs via the keyboard and mouse for the game scene. The systems comprising this should provide an interface to deal with key, mouse, and window events. Ideally, all actual input logic should be handled via external scripts that simply use these interfaces at runtime.

- [ ] #108
- [ ] #109 
- [x] #110 
- [ ] Input and Control Manager
- [ ] Player Control Scripts
- [ ] Optional: Separate player control from camera control

**Comment by The-Spaghetti-Is-Ready** [comment]
Not needed, decided against an input manager due to time constraints providing not much progress on core engine reqs
