### ISSUE TITLE
Animation Engine

### ISSUE THREAD

**Issue by Minywire** [Minywire/Bottlebrush_Engine#88]
The character animation engine may use a frame-based animation method or a skeletal method. The recommended animation method for this assignment is keyframes with linear interpolation. There is no restriction on the model file format (Collada, Blender 3D, 3ds Max 3DS, Wavefront Object, MD2, MD3, MD5, etc). The actual file format you use will be dependent on the type of animination method you choose, the modelling tool available to you or the models available to you, and your familarity with the file format. You may use third-party loading API (check http://assimp.sourceforge.net/). You may also use third-party conversion tools to prepare your models. Please cite sources and provide sufficient references.

**Comment by The-Spaghetti-Is-Ready** [comment]
Initial implementation is in. We now need a 'manager' of some sort which is able to fetch an animation index from an MD2 model. This can then come into play with AI by having a scope where the AI can set conditions which return a specific animation for an MD2 model. This return value will in turn be used in the MD2 rendering function.
