### ISSUE TITLE
Decouple Remaining Engine Components from EntryPoint

### ISSUE THREAD

**Issue by The-Spaghetti-Is-Ready** [Minywire/Bottlebrush_Engine#99]
# Problem

The Camera, Terrain and Skybox are still loose in EntryPoint. They need to be ported to the scene interface to truly make our engine modular and to reduce EntryPoint coupling. Camera implementation will need Input Manager if it is to be modularized (issue #83 ).

# Acceptance Criteria

The Scene interface holds everything needed (that we have implemented) to create a game scene.

**Comment by jdilanzo** [comment]
Should this be split up into two separate tasks e.g. Resource Manager and Scene Manager?

**Comment by The-Spaghetti-Is-Ready** [comment]
Yes, good idea

**Comment by The-Spaghetti-Is-Ready** [comment]
Solved in #122
